### ISSUE TITLE
Install fails with conda and python10

### ISSUE THREAD

**Issue by alexub** [run-house/runhouse#285]
**Describe the bug**
The following fails on a M1 Macbook Pro:

```
conda create -n runhouse python==3.10
conda activate runhouse
pip install --no-cache "runhouse[aws]"
```

The error is:
```
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/abeatson/mambaforge/envs/runhouse3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/abeatson/mambaforge/envs/runhouse3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/abeatson/mambaforge/envs/runhouse3/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/1n/t9p25xtd4sl4zxdt57hjlc7m0000gn/T/pip-build-env-obpqea6w/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

**Versions**
Please run the following and paste the output below.
```
wget https://raw.githubusercontent.com/run-house/runhouse/main/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Output:
```
python collect_env.py
Python Platform: macOS-13.4-arm64-arm-64bit
Python Version: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:27:15) [Clang 11.1.0 ]

Relevant packages:
wheel==0.42.0

sh: sky: command not found
sh: sky: command not found
```

**Comment by carolineechen** [comment]
Hi @alexub, thanks for flagging this! Looks like an issue while installing pyyaml during the awscli installation for the specific version pinned in stable right now. This should be resolved in our next release, but a couple of options to get around this for now:

1. Run pip install from the Runhouse main dev branch, which has relaxed the awscli version.
```pip install "git+https://github.com/run-house/runhouse.git#egg=runhouse[aws]"```

2. Run ``pip install runhouse`` (no aws extension), and then manually install the specific versions of awscli/boto you need.

3. First install pyyaml (5.4.1 works for me), then run ``pip install "runhouse[aws]"``

Let me know if you're still running into anything!

**Comment by carolineechen** [comment]
I just reran your commands with the new runhouse version (v0.0.15) released a few days ago and the installation should be fixed now! Closing this issue but feel free to reopen or create a new one if you're still encountering this or running into a new error 🙂
